// Custom shader file for tremor.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

tremor/87F4F3CBFB906AAEC11163E89F253BCE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/tremor/vented_5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/9D094A06FAF05C70DD37B6A45C9C33E2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/85864B4040DCC308B33A5CB87FF690DD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/227F6C1D230E025D80B7F889472844E1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/7205E037804FB4DE432D9F6FBF583C15
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/runner_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/FF007843644F03056B30640101D31B1D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/tremor/vented_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/1396C6317E5453C43C328CDBA3CBB526
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/tremor/vented_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/06D3E2D0B569649A153F61A102A97FF2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B43D0C05E3EA7333E0509790C19CB2C7
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/support_3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/1C7B6EA97DF210B8572D6F66D4275053
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/dark_metal_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/E315E7C859B3B11586174C4CF2BB01A9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03906 0.00000
	}

	{
		map textures/tremor/metal_panels.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B5B49761342E7F213413EAE2CC1BC4C4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03125 0.00000
	}

	{
		map textures/tremor/metal_panels.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/BF5BB666EB8FEB2E4015B20B80B2D6DE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/metal_panels.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/DBAF03B5195BE463C7E8042DFA9EBD11
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.07031 0.00000
	}

	{
		map textures/tremor/flat_dk.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/9D351CC5F0D8DE674F6C713991B33D0F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/BD5DA8E22D6D4EE701F0BC13BA2215AE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_5.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/03662E60F7B076E104BDF25772041413
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.17969 0.00000
	}

	{
		map textures/tremor/vented_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/E2B83F0193BD02634C04A5A87EF99330
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.56250 0.01562
	}

	{
		map textures/tremor/vented_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B9EBFFFE764C462A971AFC1183337EEB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/F2AAED05C65A1AF534475E47ABC5599C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/484376081FBBAB697D3601D634CCE978
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/194BD4FCF808C7728556E31661C6A128
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/tech_256_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/63BEC5392B84F80CB708E45A5C3C4063
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/D63F45DFE5F41719E5EEE56336DCF556
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.50000
	}

	{
		map textures/tremor/runner_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/3B7B758E5EC135D06179FEB95A709528
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/runner_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B3B160E6C92626D053CF1E9408F40BB9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.28906 0.03906
	}

	{
		map textures/tremor/runner_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/10621AF295FF2D24D03914B7CDD0CF4D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/tremor/runner_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/4CF400D6059300E540342CE5583F9533
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/BC3ED15012F517FC45E0DE5EA3A2A364
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/vented_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/43697038955CE2956617FF9A6FCC7570
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/support_3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/12CFA775628B869E829EA60F6A528123
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/dark_metal_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/5F07EBAC65AD86BE70ABCC5DEE821F68
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/titan/dark_metal_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/A78FB00FA3AAAB5CAF7769C91E39850D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/metal_panels.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/AD76F44B4F201CCD2A8848C4E1D755A1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/metal_panels.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/E8C340FC8DC135EC338447BBC283E3D1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/metal_panels.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/71D83DE9318B9C2D038F103B940AE52C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.48438 0.04688
	}

	{
		map textures/tremor/vented_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/618D47025C44BFC507555460D2C11532
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.56250 0.03125
	}

	{
		map textures/tremor/vented_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/A5642C8A2C1ACC52FBFDCB272606F1A1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/1C6F13EB277CC83DB74322E1BAC904BB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/tremor/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
	}

	{
		map textures/tremor/grate3.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

tremor/B217D46B96763744CCFB82686CE3EED9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sawtooth 0 1 0 0.5 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.59375 0.00781
	}

	{
		map textures/tremor/runner_2.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

